# .github/workflows/release.yml
name: ▫️ Reusable Release Steps - Create new version
on:
  workflow_call:
    inputs:
      release_version:
        required: true
        type: string
      node_version:
        required: false
        type: string
        default: '22'

jobs:
  create_branch_release:
    name: Creating release branch
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4 
        with:
          ref: develop
      - name: Create and push release branch
        run: |
          git fetch origin
          git checkout develop
          git pull
          git checkout -b ${{inputs.release_version}}
          git push -u origin ${{inputs.release_version}}
      - name: Merge develop -> release
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: ${{inputs.release_version}}
          commit-message: "Branch ${{inputs.release_version}} was updated with develop branch changes"

  run_ci_on_release_branch:
    needs: create_branch_release
    name: Run CI on release branch
    uses: ./.github/workflows/reusable-ci.yml # Calls our reusable CI workflow
    with:
      branch_name: ${{ inputs.release_version }}
      github_environment: staging 
      node_version: ${{ inputs.node_version }}
  # Merge release branch into staging after deployment to Vercel
  merge_branch_release_to_staging:
    # This job merges the release branch into the staging branch after deployment to Vercel
    needs: run_ci_on_release_branch
    name: Merge release branch into staging
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Mezcla release -> staging
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{inputs.release_version}}
          target-branch: staging
          commit-message: "Merge release branch ${{inputs.release_version}} into staging. Staging branch updated"

  # Deploy a Vercel Staging
  deploy_release_to_vercel_staging:
    needs: run_ci_on_release_branch # Needs to ensure the CI has passed
    if: github.event_name == 'workflow_call' # This job only runs when called from another workflow
    name: Deploy release to Vercel Staging
    uses: ./.github/workflows/reusable-vercel-deploy.yml # Calls our reusable Vercel deploy workflow
    with:
      github_environment: staging 
      vercel_environment: preview
      branch_name: staging
      prod: false

