# .github/workflows/reusable-vercel-deploy.yml
name: ▫️ Reusable Vercel Deploy (CLI)

on:
  workflow_call:
    inputs:
      github_environment:
        required: true
        type: string
      vercel_environment:
        required: true
        type: string
      prod:
        required: false
        type: boolean
        default: false
      branch_name:
        required: true
        type: string

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}
      - name: checking repo sec
        run: |
          echo ${{secrets.VERCEL_ORG_ID}} | sed 's/./& /g'
          echo ${{secrets.CONSCIA_ENVIRONMENT_CODE}} | sed 's/./& /g'
          echo ${{secrets.VERCEL_TOKEN}} | sed 's/./& /g'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ inputs.vercel_environment }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: |
          if [ "${{ inputs.prod }}" = "true" ]; then
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel build --target=${{ inputs.vercel_environment }} --token=${{ secrets.VERCEL_TOKEN }}
          fi
      - name: Deploy Project Artifacts to Vercel
        run: |
          if [ "${{ inputs.prod }}" = "true" ]; then
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --prebuilt --target=${{ inputs.vercel_environment }} --token=${{ secrets.VERCEL_TOKEN }}
          fi
